name: VOXSCIO
favicon: null
layout_spectrum: 0.29671261995099485
typography_spectrum: 0.9468059791252017
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8239440936595201
  lightness: 0.1943665670696646
  saturation: 0.8879750552587211
  rhythmicContrast: 0.929471853422001
purpose: []
