name: VOXSCIO
favicon: null
layout_spectrum: 0.75199
typography_spectrum: 0.47502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#373535'
    - '#d1383b'
    - '#ecb2a2'
    - '#f6f6f6'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.929471853422001
purpose: []
